// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJje5bqq5-OmOGpeJeBd5qeKpWDKLHRgg',
    appId: '1:553029417276:web:30a510302cf4fbf8d48639',
    messagingSenderId: '553029417276',
    projectId: 'mpd-finals',
    authDomain: 'mpd-finals.firebaseapp.com',
    storageBucket: 'mpd-finals.firebasestorage.app',
    measurementId: 'G-FRQCBEZMC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEtv61C-HPeoKdzHMER2sCSNHmYHRYyzY',
    appId: '1:553029417276:android:0c759c04dace166dd48639',
    messagingSenderId: '553029417276',
    projectId: 'mpd-finals',
    storageBucket: 'mpd-finals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCT6gYfX4xC2NUjHdzpzXmfRfsp3WWsIU',
    appId: '1:553029417276:ios:d96bfe10977470dfd48639',
    messagingSenderId: '553029417276',
    projectId: 'mpd-finals',
    storageBucket: 'mpd-finals.firebasestorage.app',
    androidClientId: '553029417276-sbtk19jj9885kb62jgpqguptorn9is5f.apps.googleusercontent.com',
    iosClientId: '553029417276-q5l171q1ifvr4pta19n2t7n4prf0479u.apps.googleusercontent.com',
    iosBundleId: 'com.example.universityReviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCT6gYfX4xC2NUjHdzpzXmfRfsp3WWsIU',
    appId: '1:553029417276:ios:d96bfe10977470dfd48639',
    messagingSenderId: '553029417276',
    projectId: 'mpd-finals',
    storageBucket: 'mpd-finals.firebasestorage.app',
    androidClientId: '553029417276-sbtk19jj9885kb62jgpqguptorn9is5f.apps.googleusercontent.com',
    iosClientId: '553029417276-q5l171q1ifvr4pta19n2t7n4prf0479u.apps.googleusercontent.com',
    iosBundleId: 'com.example.universityReviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJje5bqq5-OmOGpeJeBd5qeKpWDKLHRgg',
    appId: '1:553029417276:web:7057f69b1f7867e4d48639',
    messagingSenderId: '553029417276',
    projectId: 'mpd-finals',
    authDomain: 'mpd-finals.firebaseapp.com',
    storageBucket: 'mpd-finals.firebasestorage.app',
    measurementId: 'G-FVB62R0FP1',
  );

}